bear_vision/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('lava_light.urls', namespace="lava_light")),
    # path("insights/", include("trading_insights.urls")),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lava_light/urls.py
from django.urls import path, include
from django.apps import apps

from lava_light.views import (
    get_list_view, get_detail_view,
    get_update_view, get_create_view,
    HomeView, NotificationsView,
    SignupView, LoginView, LogoutView,
    PasswordReset
)
from lava_light import settings as light_settings

app_name = "lava_light"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('notifications', NotificationsView.as_view(), name='notifications'),
    path('signup', SignupView.as_view(), name='signup'),
    path('login', LoginView.as_view(), name='login'),
    path('password_reset', PasswordReset.as_view(), name="password_reset"),
    path('logout', LogoutView.as_view(), name='logout'),
]


for model_name in light_settings.MAIN_MENU_ITEMS:
    model = apps.get_model(model_name)
    app_label = model._meta.app_label
    model_name = model._meta.model_name

    urlpatterns.extend([
        path(
            f'{app_label}/{model_name}/',
            get_list_view(model).as_view(), name=f'{app_label}_{model_name}_list'
        ),
        path(
            f'{app_label}/{model_name}/create/',
            get_create_view(model).as_view(), name=f'{app_label}_{model_name}_create'
        ),
        path(
            f'{app_label}/{model_name}/<int:pk>/',
            get_detail_view(model).as_view(), name=f'{app_label}_{model_name}_detail'
        ),
        path(
            f'{app_label}/{model_name}/<int:pk>/update/',
            get_update_view(model).as_view(), name=f'{app_label}_{model_name}_update'
        ),
    ])

trading_insights/urls.py
from django.urls import path

from trading_insights.views import ScenarioListView


app_name = "trading_insights"


# urlpatterns = [
#     path('scenario', ScenarioListView.as_view(), name='scenarios'),
# ]

lava_light/forms.py
import importlib

from django.utils.translation import gettext_lazy as _
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


def try_import_form(model, model_form_suffix="Form"):

    try:
        app_label = model._meta.app_label
        model_name = model._meta.model.__name__
        forms_module = importlib.import_module(f"{app_label}.forms")
        CustomModelListView = getattr(
            forms_module, "%s%s" % (model_name, model_form_suffix)
        )
        return CustomModelListView
    except (ImportError, AttributeError) as e:
        return None


def get_model_form(model, fields=None, action=None):

    if fields is None:
        fields = [
            f.name for f in model._meta.local_fields if f.editable
        ]

    CustomForm = try_import_form(model, model_form_suffix="Form")
    if CustomForm:
        return CustomForm

    class GenericBaseModelForm(forms.ModelForm):
        class Meta:
            pass

        Meta.model = model
        Meta.fields = fields

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.helper = FormHelper()

            model_name = model._meta.model_name.lower()
            self.helper.form_id = f"{model_name}_form"
            self.helper.form_class = f"{model_name}_form form col-sm-12 col-md-12 col-lg-8 form-horizontal"
            self.helper.form_method = "POST"
            self.helper.label_class = "col-lg-2"
            self.helper.field_class = "col-lg-10"
            if action and action == "update":
                self.helper.add_input(Submit("submit", _("Modifier")))
            elif action and action == "create":
                self.helper.add_input(Submit("submit", _("Ajouter")))

    return GenericBaseModelForm

lava_light/views/generic_views.py
import importlib

from django.shortcuts import redirect
from django.views.generic import (
    DetailView as BaseDetailView,
    ListView as BaseListView,
    UpdateView as BaseUpdateView,
    CreateView as BaseCreateView,
    TemplateView, RedirectView
)
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from lava_light.utils import Result
from lava_light.forms import get_model_form


def try_import_view(model, model_view_suffix="View"):

    try:
        app_label = model._meta.app_label
        model_name = model._meta.model.__name__
        views_module = importlib.import_module(f"{app_label}.views")
        CustomModelListView = getattr(
            views_module, "%s%s" % (model_name, model_view_suffix)
        )
        return CustomModelListView
    except (ImportError, AttributeError) as e:
        return None


class BaseViewMixin:

    def get_template_names(self):
        """
        This method checks for template files in a specific order,
        Let's say you want to get the list template of your model `polls.Bar`.
        The order in which files are going to be retrieved is:
            1. polls/bar_list.html  # Model specific template file.
            2. polls/generics/list.html  # If you want to provide a shared list.html file
                between all models of an app.
            3. lava_light/generics/list.html  # The default file that is chosen if none of
                the above was found.
        """

        names = super().get_template_names()

        if hasattr(self, 'object_list'):
            if hasattr(self.object_list, 'model'):
                opts = self.object_list.model._meta
                template_name_suffix = self.template_name_suffix[1:]  # _list > list
                names.append("%s/generics/%s.html" % (opts.app_label, template_name_suffix))

            if self.generic_template_name:
                names.append(self.generic_template_name)
        return names


class ProtectedBaseViewMixin(BaseViewMixin):

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ProtectedTemplateView(ProtectedBaseViewMixin, TemplateView):
    pass


class ProtectedRedirectView(ProtectedBaseViewMixin, RedirectView):
    pass


class BaseProtectedModelViewMixin(ProtectedBaseViewMixin):

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["model_verbose_name"] = self.model._meta.verbose_name
        context["model_verbose_name_plural"] = self.model._meta.verbose_name_plural
        available_fields = self.model._meta.get_fields(include_parents=True)
        context["model_fields"] = available_fields
        context["list_url"] = self.model.get_list_url()
        context["create_url"] = self.model.get_create_url()
        return context


class ListView(BaseProtectedModelViewMixin, BaseListView):

    generic_template_name = "lava_light/generics/list.html"
    paginate_by = 10

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        available_fields = self.model._meta.get_fields(include_parents=True)
        if hasattr(self.model, "get_list_display"):
            available_fields = self.model.get_list_display()
        context["model_fields"] = available_fields
        context["view"] = "list"
        return context


class DetailView(BaseProtectedModelViewMixin, BaseDetailView):

    template_name = "lava_light/generics/detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["view"] = "details"
        return context

    def post(self, request, *args, **kwargs):
        action = request.POST.get('action', None)
        if action == "delete":
            instance = self.get_object()
            result : Result = instance.delete()
            if result.is_success:
                messages.success(request, result.message)
            else:
                messages.error(request, result.message)

        return redirect(self.model.get_list_url())


class CreateView(BaseProtectedModelViewMixin, BaseCreateView):

    template_name = "lava_light/generics/form.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["view"] = "create"
        return context


class UpdateView(BaseProtectedModelViewMixin, BaseUpdateView):

    template_name = "lava_light/generics/form.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["view"] = "update"
        return context

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


def get_list_view(model):

    # Check if the model has a custom view first
    CustomModelListView = try_import_view(model, "ListView")
    if CustomModelListView:
        return CustomModelListView

    # Otherwise, create a generic view
    class GenericListView(ListView):

        def __init__(self, **kwargs):
            self.model = model
            self.paginate_by = 20

            super().__init__()

    return GenericListView


def get_detail_view(model):

    form_class = get_model_form(model, fields=None)

    # Check if the model has a custom view first
    CustomModelDetailView = try_import_view(model, "DetailView")
    if CustomModelDetailView:
        return CustomModelDetailView

    class GenericDetailView(DetailView):

        def __init__(self, **kwargs):
            self.model = model
            self.form_class = form_class

            super().__init__()

    return GenericDetailView


def get_create_view(model):

    form_class = get_model_form(model, fields=None, action="create")

    # Check if the model has a custom view first
    CustomModelCreateView = try_import_view(model, "CreateView")
    if CustomModelCreateView:
        return CustomModelCreateView

    class GenericCreateView(CreateView):

        def __init__(self, **kwargs):
            self.model = model
            self.form_class = form_class

            super().__init__()

    return GenericCreateView


def get_update_view(model):

    form_class = get_model_form(model, fields=None, action="update")

    # Check if the model has a custom view first
    CustomModelUpdateView = try_import_view(model, "UpdateView")
    if CustomModelUpdateView:
        return CustomModelUpdateView

    class GenericUpdateView(UpdateView):

        def __init__(self, **kwargs):
            self.model = model
            self.form_class = form_class

            super().__init__()

    return GenericUpdateView

lava_light/views/main_views.py
from django.shortcuts import redirect, render, reverse
from django.views.generic import (
    TemplateView,
    RedirectView
)
from django.contrib.auth.forms import (
    AuthenticationForm
)
from django.contrib.auth.views import (
    LoginView as BaseLoginView,
    LogoutView as BaseLogoutView,
    PasswordResetView, PasswordResetConfirmView,
    PasswordResetDoneView, PasswordResetCompleteView
)

from lava_light.views.generic_views import (
    ProtectedTemplateView, ProtectedRedirectView
)


class HomeView(ProtectedTemplateView):
    template_name = "lava_light/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context["latest_articles"] = Article.objects.all()[:5]
        return context


class NotificationsView(ProtectedTemplateView):
    template_name = "lava_light/notifications.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context["latest_articles"] = Article.objects.all()[:5]
        context["model_verbose_name"] = "Notification"
        context["model_verbose_name_plural"] = "Notifications"
        return context


class SignupView(TemplateView):
    template_name = "lava_light/signup.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


class LoginView(BaseLoginView):
    template_name = "lava_light/login.html"

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     return context

    # def post(self, request, *args, **kwargs):
    #     return super().post(request, *args, **kwargs)


class PasswordReset(PasswordResetView):

    template_name = "lava_light/pwd_reset.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


class LogoutView(BaseLogoutView):

    template_name = "lava_light/login.html"

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

lava_light/templates/lava_light/index.html
{% extends 'lava_light/index_empty.html' %}
{% load lava_light_tags static i18n %}

{% block app %}
<div class="layout">
    <!-- Header START -->
    <div class="header">
        <div class="logo logo-dark" style="
            display: flex;
            align-items: center;
            justify-content: center;
        ">
            <a href="{% url 'lava_light:home' %}">
                <img src={% static 'enlink/assets/images/logo/logo.png' %} width="200" alt="Logo">
                <img class="logo-fold" src={% static 'enlink/assets/images/logo/logo-fold.png' %} alt="Logo">
            </a>
        </div>
        <div class="logo logo-white" style="
            align-items: center;
            justify-content: center;
        ">
            <a href="{% url 'lava_light:home' %}">
                <img src={% static 'enlink/assets/images/logo/logo-white.png' %} width="200" alt="Logo">
                <img class="logo-fold" src={% static 'enlink/assets/images/logo/logo-fold-white.png' %} alt="Logo">
            </a>
        </div>
        <div class="nav-wrap">
            <ul class="nav-left">
                <li class="desktop-toggle">
                    <a href="javascript:void(0);">
                        <i class="anticon"></i>
                    </a>
                </li>
                <li class="mobile-toggle">
                    <a href="javascript:void(0);">
                        <i class="anticon"></i>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0);" data-toggle="modal" data-target="#search-drawer">
                        <i class="anticon anticon-search"></i>
                    </a>
                </li>
            </ul>
            <ul class="nav-right">
                <li class="dropdown dropdown-animated scale-left p-l-5">
                    <a href="javascript:void(0);" data-toggle="dropdown">
                        <i class="anticon anticon-bell notification-badge"></i>
                    </a>
                    <div class="dropdown-menu pop-notification">
                        <div class="p-v-15 p-h-25 border-bottom d-flex justify-content-between align-items-center">
                            <p class="text-dark font-weight-semibold m-b-0">
                                <i class="anticon anticon-bell"></i>
                                <span class="m-l-10">Notification</span>
                            </p>
                            <a class="btn-sm btn-default btn" href="{% url 'lava_light:notifications' %}">
                                <small>View All</small>
                            </a>
                        </div>
                        <div class="relative">
                            <div class="overflow-y-auto relative scrollable" style="max-height: 300px">
                                {% for notification in request.user.notifications.all %}
                                    <a href="javascript:void(0);" class="dropdown-item d-block p-15 border-bottom">
                                        <div class="d-flex">
                                            <div class="avatar avatar-blue avatar-icon">
                                                <i class="anticon anticon-mail"></i>
                                            </div>
                                            <div class="m-l-15">
                                                <p class="m-b-0 text-dark">You received a new message</p>
                                                <p class="m-b-0"><small>8 min ago</small></p>
                                            </div>
                                        </div>
                                    </a>
                                {% empty %}
                                    <a href="javascript:void(0);" class="dropdown-item d-block p-15 border-bottom">
                                        <div class="d-flex">
                                            <div class="m-l-15">
                                                <!-- <p class="m-b-0 text-dark">You received a new message</p> -->
                                                <p class="m-b-0"><small>You have no notifications for now</small></p>
                                            </div>
                                        </div>
                                    </a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </li>
                <li class="dropdown dropdown-animated scale-left p-l-5">
                    <div class="pointer" data-toggle="dropdown">
                        {% if request.user.photo %}
                            <div class="avatar avatar-lg avatar-image">
                                <img src="{{ request.user.photo.url }}" alt="">
                            </div>
                        {% else %}
                            <div class="avatar avatar-icon avatar-blue">
                                <i class="anticon anticon-user"></i>
                            </div>
                        {% endif %}
                    </div>
                    <div class="p-b-15 p-t-20 dropdown-menu pop-profile">
                        <div class="p-h-20 p-b-15 m-b-10 border-bottom">
                            <div class="d-flex">
                                {% if request.user.photo %}
                                    <div class="avatar avatar-lg avatar-image">
                                        <img src="{{ request.user.photo.url }}" alt="">
                                    </div>
                                {% else %}
                                    <div class="avatar avatar-icon avatar-blue">
                                        <i class="anticon anticon-user"></i>
                                    </div>
                                {% endif %}
                                <div class="m-l-10">
                                    <p class="m-b-0 text-dark font-weight-semibold">{{ request.user.first_name }} {{ request.user.last_name }}</p>
                                    <p class="m-b-0 opacity-07">{{ request.user }}</p>
                                </div>
                            </div>
                        </div>
                        <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                            <div class="d-flex align-items-center justify-content-between">
                                <div>
                                    <i class="anticon opacity-04 font-size-16 anticon-user"></i>
                                    <span class="m-l-10">Edit Profile</span>
                                </div>
                                <i class="anticon font-size-10 anticon-right"></i>
                            </div>
                        </a>
                        <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                            <div class="d-flex align-items-center justify-content-between">
                                <div>
                                    <i class="anticon opacity-04 font-size-16 anticon-lock"></i>
                                    <span class="m-l-10">Account Setting</span>
                                </div>
                                <i class="anticon font-size-10 anticon-right"></i>
                            </div>
                        </a>
                        <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                            <div class="d-flex align-items-center justify-content-between">
                                <div>
                                    <i class="anticon opacity-04 font-size-16 anticon-project"></i>
                                    <span class="m-l-10">Projects</span>
                                </div>
                                <i class="anticon font-size-10 anticon-right"></i>
                            </div>
                        </a>
                        <a href="{% url 'lava_light:logout' %}" class="dropdown-item d-block p-h-15 p-v-10">
                            <div class="d-flex align-items-center justify-content-between">
                                <div>
                                    <i class="anticon opacity-04 font-size-16 anticon-logout"></i>
                                    <span class="m-l-10">Logout</span>
                                </div>
                                <i class="anticon font-size-10 anticon-right"></i>
                            </div>
                        </a>
                    </div>
                </li>
                {% comment %}<li class="p-l-5">
                    <a href="javascript:void(0);" data-toggle="modal" data-target="#quick-view">
                        <i class="anticon anticon-appstore"></i>
                    </a>
                </li>{% endcomment %}
            </ul>
        </div>
    </div>
    <!-- Header END -->

    <!-- Side Nav START -->
    {% include 'lava_light/sidebar_nav.html' %}
    <!-- Side Nav END -->

    <!-- Page Container START -->
    <div class="page-container">

        <!-- Content Wrapper START -->
        <div class="main-content">
            {% block page_header %}
            <div class="page-header-wrapper">
                <div class="page-header">
                    {% if object %}
                        <h2 class="header-title">{{ object }}</h2>
                    {% else %}
                        <h2 class="header-title">{{ model_verbose_name_plural }}</h2>
                    {% endif %}
                    <div class="header-sub-title">
                        <nav class="breadcrumb breadcrumb-dash">
                            <a href="{% url 'lava_light:home' %}" class="breadcrumb-item">
                                <i class="anticon anticon-home m-r-5"></i> {% trans 'Accueil' %}
                            </a>
                            {% if object and view == "update" %}
                                <a class="breadcrumb-item" href="{{ list_url }}">{{ model_verbose_name_plural }}</a>
                                <a class="breadcrumb-item" href="{{ object.get_absolute_url }}">{{ object }}</a>
                                <span class="breadcrumb-item active">{% trans 'Modification' %}</span>
                            {% elif object and view == "details" %}
                                <a class="breadcrumb-item" href="{{ list_url }}">{{ model_verbose_name_plural }}</a>
                                <span class="breadcrumb-item active">{{ object }}</span>
                            {% elif view == "create" %}
                                <a class="breadcrumb-item" href="{{ list_url }}">{{ model_verbose_name_plural }}</a>
                                <span class="breadcrumb-item active">{% trans "Création" %}</span>
                            {% else %}
                                <span class="breadcrumb-item active">{{ model_verbose_name_plural }}</span>
                            {% endif %}
                        </nav>
                    </div>
                </div>
                <div class="header-actions">
                    {% block page_header_actions %}
                    {% endblock page_header_actions %}
                </div>
            </div>
            {% endblock page_header %}

            <!-- Content goes Here -->
            {% block main %}
            {% endblock main %}
        </div>
        <!-- Content Wrapper END -->

        <!-- Footer START -->
        <footer class="footer">
            <div class="footer-content">
                <p class="m-b-0">Copyright © 2022 EKBlocks. All rights reserved.</p>
                <!-- <span>
                    <a href="" class="text-gray m-r-15">Term &amp; Conditions</a>
                    <a href="" class="text-gray">Privacy &amp; Policy</a>
                </span> -->
            </div>
        </footer>
        <!-- Footer END -->

    </div>
    <!-- Page Container END -->

    <!-- Search Start-->
    <div class="modal modal-left fade search" id="search-drawer">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header justify-content-between align-items-center">
                    <h5 class="modal-title">Search</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <i class="anticon anticon-close"></i>
                    </button>
                </div>
                <div class="modal-body scrollable">
                    <div class="input-affix">
                        <i class="prefix-icon anticon anticon-search"></i>
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <!-- Content goes Here -->
                </div>
            </div>
        </div>
    </div>
    <!-- Search End-->

    {% comment %}<!-- Quick View START -->
    <div class="modal modal-right fade quick-view" id="quick-view">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header justify-content-between align-items-center">
                    <h5 class="modal-title">Quick View</h5>
                </div>
                <div class="modal-body scrollable">
                    <!-- Content goes Here -->
                </div>
            </div>
        </div>
    </div>
    <!-- Quick View END -->{% endcomment %}
</div>
{% endblock app %}

lava_light/templates/lava_light/index_empty.html
{% load lava_light_tags static i18n %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        {{ p.title|default:'Lava Light home page' }}
    </title>

    <!-- Favicon -->
    <link rel="shortcut icon" href={% static 'enlink/assets/images/logo/favicon.png' %}>

    <!-- page css -->
    {% block page_css %}
    {% endblock page_css %}

    <!-- Core css -->
    <link href={% static 'enlink/assets/css/app.min.css' %} rel="stylesheet">

    <!-- Custom css -->
    <link href={% static 'enlink/assets/css/custom.css' %} rel="stylesheet">

    <!-- Extra /Page styles -->
    {% block extra_css %}
    {% endblock extra_css %}

</head>

<body>
    <div class="app">
        {% block app %}

        {% endblock app %}
    </div>


    <!-- Core Vendors JS -->
    <script src={% static 'enlink/assets/js/vendors.min.js' %}></script>

    <!-- Page js -->
    {% block page_js %}
    {% endblock page_js %}

    <!-- Core JS -->
    <script src={% static 'enlink/assets/js/app.min.js' %}></script>

    <!-- Messages toast -->
    <div class="notification-toast top-right" id="notification-toast"></div>
    <script>
        function showToast(tag="primary", message) {
            let title = "{% trans 'Info' %}";
            let class_name = tag;

            if (tag == "success") {
                title =  "{% trans 'Succès' %}";
            }
            else if (tag == "danger") {
                title =  "{% trans 'Erreur' %}";
            }
            else if (tag == "warning") {
                title =  "{% trans 'Avertissement' %}";
            }

            var toastHTML = `<div class="toast fade hide" data-delay="5000">
                <div class="toast-header">
                    <i class="anticon anticon-info-circle text-${class_name} m-r-5"></i>
                    <strong class="mr-auto">${title}</strong>
                    <small>{% trans 'Aujourd\'hui' %}</small>
                    <button type="button" class="ml-2 close" data-dismiss="toast" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="toast-body">
                    ${message}
                </div>
            </div>`;

            $('#notification-toast').append(toastHTML);
            $('#notification-toast .toast').toast('show');
            setTimeout(function(){
                $('#notification-toast .toast:first-child').remove();
            }, 5000);
        }

        {% for message in messages %}
            alert("{{ message|safe|capfirst }}");
            showToast(
                {% if message.tags %}"{{ message.tags }}"{% endif %},
                "{{ message|capfirst }}"
            )
        {% endfor %}
    </script>

    <!-- Extra js -->
    {% block extra_js %}
    {% endblock extra_js %}

</body>

</html>

lava_light/templates/lava_light/notifications.html
{% extends 'lava_light/index.html' %}
{% load static lava_light_tags %}

{% block page_css %}
    <link href="{% static 'enlink/assets/vendors/datatables/dataTables.bootstrap.min.css' %}" rel="stylesheet">
{% endblock page_css %}

{% block page_header_actions %}
    <a class="btn btn-primary" href="{{ create_url }}">Create {{ model_verbose_name }}</a>
{% endblock page_header_actions %}

{% block main %}
    <div class="card">
        <div class="card-body">
            <table id="data-table" class="table">
                <thead>
                    <tr>
                        <th>Notifications</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><a href="#">Alert form Admin</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock main %}

{% block page_js %}
    <script src="{% static 'enlink/assets/vendors/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'enlink/assets/vendors/datatables/dataTables.bootstrap.min.js' %}"></script>
{% endblock page_js %}

{% block extra_js %}
    <script>
        $('#data-table').DataTable();
    </script>
{% endblock extra_js %}

lava_light/templates/lava_light/signup.html
{% extends 'lava_light/index_empty.html' %}

{% block main %}
    <div class="card">
        <div class="card-body">

        </div>
    </div>
{% endblock main %}